apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-portal-deploy
spec:
  selector:
    matchLabels:
      app: student-portal
  replicas: 1
  template:
    metadata:
      labels:
        app: student-portal
    spec:
      containers:
      - name: student-portal
        image: YOUR_DOCKER_REGISTRY/student-portal:v1
        ports:
        - containerPort: 5000
